### ISSUE TITLE
cbsh is broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-shell#5]
```
(cpy362_1) oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-fabric-shell$ cbsh
Crossbar.io Fabric Shell: v17.8.2-dev1
Active user profile: default
User public key loaded: /home/oberstet/.cbf/default.pub
User private key loaded: /home/oberstet/.cbf/default.priv
Connecting to ws://localhost:9000/ws ..
Entering event loop ..
Future exception was never retrieved
future: <Future finished exception=AttributeError("'UserKey' object has no attribute 'public_key'",)>
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/txaio/txaio/aio.py", line 365, in as_future
    res = fun(*args, **kwargs)
  File "/home/oberstet/scm/crossbario/crossbar-fabric-shell/crossbarfabricshell/client.py", line 64, in onConnect
    u'pubkey': self._key.public_key(),
AttributeError: 'UserKey' object has no attribute 'public_key'
^C(cpy362_1) oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-fabric-shell$ 
```

**Comment by oberstet** [comment]
this is fixed
